#version: "3.9"
name: ${PROJECT_NAME}

services:
  db:
    image: ${MYSQL_IMAGE}
    container_name: ${PROJECT_NAME}-db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      #MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
        #MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      - ./secrets/${ENV}/db_password:/run/secrets/db_password:ro 
    ports:
      - "${DB_HOST_PORT}:${DB_CONTAINER_PORT}"
    networks:
      - app-network

  backend:
    container_name: ${PROJECT_NAME}-backend
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}
      SPRING_DATASOURCE_URL: jdbc:mysql://db:${DB_CONTAINER_PORT}/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
        #SPRING_DATASOURCE_PASSWORD_FILE: /run/secrets/db_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      APP_UPLOAD_BASE_PATH: ${APP_BASE_PATH}/backend/
        #SPRING_DATASOURCE_PASSWORD_FILE: /run/secrets/db_password
    command: >
      sh -c "
      export SPRING_DATASOURCE_PASSWORD=$(cat /run/secrets/db_password) &&
      exec java -jar app.jar
      "
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8081 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
    volumes:
      - ./volumes/backend/logs:/app/logs
      - ./backend/upload:${APP_BASE_PATH}/backend/upload
      - ./secrets/${ENV}/db_password:/run/secrets/db_password:ro
        #ports:
        #- "${BACKEND_HOST_PORT}:${BACKEND_CONTAINER_PORT}"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    container_name: ${PROJECT_NAME}-frontend
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "nginx -t || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - app-network

  reverse-proxy:
    image: ${PROXY_IMAGE}
    container_name: ${PROJECT_NAME}-proxy
    restart: always
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 5s
      retries: 3
    env_file:
      - env/common.env
      - env/dev.env
    volumes:
      - ./reverse-proxy/nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./certs:/etc/nginx/certs:ro
    ports:
      - "${PROXY_HOST_PORT}:${PROXY_CONTAINER_PORT}"
    networks:
      - app-network


networks:
  app-network:
    external: true
    name: ${APP_NETWORK}
