services:
  db:
    image: ${MYSQL_IMAGE}
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./secrets/${ENV}/db_password:/run/secrets/db_password:ro
    ports:
      - "${DB_HOST_PORT}:${DB_CONTAINER_PORT}"
    networks:
      - app-network

volumes:
  mysql-data:
    name: ${COMPOSE_PROJECT_NAME}_mysql-data

networks:
  app-network:

