services:
  reverse-proxy:
    image: nginx:stable-alpine
    restart: always
    environment:
      PROXY_CONTAINER_PORT: ${PROXY_CONTAINER_PORT}
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - ./reverse-proxy/nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./certs:/etc/nginx/certs:ro
    ports:
      - "${PROXY_HOST_PORT}:${PROXY_CONTAINER_PORT}"
    networks:
      - app-network

networks:
  app-network:

