services:
  prometheus:
    image: prom/prometheus:v2.48.1
    container_name: prometheus_dba
      #user: "1004:1004"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        #- ./volumes/prometheus:/prometheus
      - prometheus_data:/prometheus
    ports:
      - "4090:9090"
    restart: always
    networks:
      - dbaalld-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_dba
    user: "0"
    restart: always
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_PASS}
      GF_PATHS_DATA: /var/lib/grafana
    volumes:
      - ./volumes/grafana:/var/lib/grafana
      - ./monitoring/grafana-provisioning:/etc/grafana/provisioning
    ports:
      - "4300:3000"
    networks:
      - dbaalld-network

  blackbox:
    image: prom/blackbox-exporter:latest
    container_name: blackbox_exporter
    ports:
      - "4115:9115"
    networks:
      - dbaalld-network

  mysql-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysql_exporter
    user: "1004"
    command:
      - "--config.my-cnf=/etc/mysql-exporter/.my.cnf"
    volumes:
      - ./monitoring/mysql-exporter.cnf:/etc/mysql-exporter/.my.cnf:ro
      - ./volumes/mysql-exporter:/var/lib/mysql-exporter
    ports:
      - "4104:9104"
    networks:
      - dbaalld-network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    command:
      - "--docker_only=true"
      - "--enable_metrics=cpu,memory,diskIO,network,process,percpu"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
    ports:
      - "4180:8080"
    networks:
      - dbaalld-network

networks:
  dbaalld-network:
    external: true

volumes:
  prometheus_data:
