name: ${PROJECT_NAME}-db

services:
  db:
    image: ${MYSQL_IMAGE}
    container_name: ${PROJECT_NAME}-db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      - ./secrets/${ENV}/db_password:/run/secrets/db_password:ro
    ports:
      - "${DB_HOST_PORT}:${DB_CONTAINER_PORT}"
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: ${APP_NETWORK}

